### PR TITLE
bugfix for Go 1.16.2: add transitive requires

### PR DESCRIPTION
**Pull request by amnonbc**
add transative requires.

This should fix the build failure in
https://github.com/redsift/sift-dmarc-insights/pull/1393

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
Cool, I'll give it a try

**Comment by deepakprabhakara** [comment]
@amnonbc better but eventually fails with an issue with go-mangosock which used the sandbox
```
Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 cmd/run/run.go:12:2: no required module provides package github.com/redsift/go-mangosock; to add it:
Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 	go get github.com/redsift/go-mangosock
Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 cmd/run/run.go:13:2: no required module provides package github.com/redsift/go-mangosock/nano; to add it:
Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 	go get github.com/redsift/go-mangosock/nano
Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 install.go:104: Building sandbox failed: exit status 
```

**Comment by amnonbc** [comment]
> @amnonbc better but eventually fails with an issue with go-mangosock which used the sandbox
> 
> ```
> Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 cmd/run/run.go:12:2: no required module provides package github.com/redsift/go-mangosock; to add it:
> Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 	go get github.com/redsift/go-mangosock
> Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 cmd/run/run.go:13:2: no required module provides package github.com/redsift/go-mangosock/nano; to add it:
> Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 	go get github.com/redsift/go-mangosock/nano
> Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 install.go:104: Building sandbox failed: exit status 
> ```

Hmmm.
Do we need the all the dependencies of dependencies etc...
I'll have a look tomorrow morning...

**Comment by amnonbc** [comment]
> > @amnonbc better but eventually fails with an issue with go-mangosock which used the sandbox
> > ```
> > Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 cmd/run/run.go:12:2: no required module provides package github.com/redsift/go-mangosock; to add it:
> > Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 	go get github.com/redsift/go-mangosock
> > Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 cmd/run/run.go:13:2: no required module provides package github.com/redsift/go-mangosock/nano; to add it:
> > Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 	go get github.com/redsift/go-mangosock/nano
> > Mar 20 19:32:59 gp14.stg.redsift.tech k8s_dagger-rt_dagger-rt-6c677f99 install.go:104: Building sandbox failed: exit status 
> > ```
> 
> Hmmm.
> Do we need the all the dependencies of dependencies etc?
> I'll have a look tomorrow morning...

This is strange
`github.com/redsift/go-mangosock` should be included in `/build/go.mod` which comes from `https://github.com/redsift/sandbox-go/blob/master/go.mod`  when the image is built.

I have updated to go-mangosock version.
@deepakprabhakara  is there any way you can get me the `/build/go.mod` and the sift `go.mod` when it fails?

**Comment by amnonbc** [comment]
```
STG gp14.stg.redsift.tech (10.72.77.213) ~........................................................................................................................................
# docker run quay.io/redsift/sandbox-go-rocksdb:v5.18.3-go1.16.2-beta cat /build/go.mod
/bin/cat: /bin/cat: cannot execute binary file
```

**Comment by amnonbc** [comment]
```
STG gp14.stg.redsift.tech (10.72.77.213) ~........................................................................................................................................
# docker run -it quay.io/redsift/sandbox-go-rocksdb:v5.18.3-go1.16.2-beta
root@c980b46885a5:/run/sandbox/sift# cat /build/go.mod
module github.com/redsift/sandbox-go

go 1.16

require (
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/redsift/go-mangosock v0.1.2
	github.com/redsift/go-sandbox-rpc v0.1.0
	github.com/stretchr/testify v1.2.2
	golang.org/x/mod v0.4.0
)

replace server => /run/sandbox/sift/server
root@c980b46885a5:/run/sandbox/sift#
```
Looks OK - go-mongosock is there.

**Comment by deepakprabhakara** [comment]
@amnonbc Looks like you are replacing requires as opposed to copying them over.

**Review by deepakprabhakara — APPROVED** [review]

**Pull request merged**
